version: '2'

services:
  mysql:
    image: mariadb:5
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:php7.2
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: password

  cli:
    image: wordpress:cli-php7.2
    volumes:
      - .:/var/www/html

volumes:
  mysql_data:
